# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec673909fc3f03bb005caa7ee80c7e6142b83dcca2058e0666f1a1c8785c899cd183c5149dbb576e9e6b647e4693a7336890b425556c57e1c89d01a434ecec72

test:
  secret_key_base: 1086b6fd81966348bd58412ac0a84d9a536285eea315f8db2032c9b5534ce847e86e33a62acd768521d21fbb926193234bef2b629321d6cbca95ea8bfcdffd3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
